### ISSUE TITLE
Change "popular" dataset sort to use number of approved users (or the like)

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#275]
And add ability to sort by "Rating".

Disambiguating the two.

**Comment by remomueller** [comment]
To continue on our discussion, for both tools and datasets, the rating should be affected by a few factors. Essentially we can have views by user count as implicit votes at 3 stars, and weight by publish date to account for more users seeing older datasets/tools.

**Comment by remomueller** [comment]
To follow up on this, the review ratings are now hidden, so popular should be based on the number of approved users on the datasets. This number should however be cached on the datasets table since it would be a join across a few tables.
