### ISSUE TITLE
CCSHS variable count disagrees from dataset index

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#354]
![image](https://user-images.githubusercontent.com/707167/58657438-456a5500-82ec-11e9-8f6a-1181595d116d.png)

![image](https://user-images.githubusercontent.com/707167/58657456-4bf8cc80-82ec-11e9-9122-560f417239f9.png)

382 vs 366 variables. I just pushed a new dataset versio today, though I think the discrepancy existed prior. I didn't locate this on any other datasets. Wasn't sure how to refresh the count on the datasets index.

**Comment by remomueller** [comment]
The following variables didn't have a folder assigned to them (`nil`), and weren't showing up in the search. I've updated them to all be under the "Spectral Analysis" folder. This accounts for the 16 variable difference between the counts.

```
["delta_lognrem", "delta_nrem", "beta_nrem", "alpha_sleep", "beta_lognrem", "beta_logsleep", "delta_logsleep", "fastsigma_lognrem", "fastsigma_sleep", "sigma_logsleep", "alpha_logsleep", "beta_sleep", "delta_sleep", "fastsigma_nrem", "fastsigma_logsleep", "sigma_lognrem"]
```
