### ISSUE TITLE
Add redirect for old SpectralTrainFig tool URL to GitHub repository

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#355]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5976521/pdf/nihms925362.pdf

The paper contains the following URL, which is no longer active: https://www.sleepdata.org/community/tools/nsrrspectraltrainfig  

Manually redirect users coming to this URL to the GitHub repository here: https://github.com/nsrr/SpectralTrainFig

**Comment by dguettler** [comment]
https://github.com/nsrr/sleepdata.org/pull/357

**Comment by mrueschman** [comment]
Whoops, I made a mistake - the link in the paper actually points to this old URL - https://www.sleepdata.org/community/tools/nsrr-spectraltrainfig

(Add dash between 'nsrr' and 'spectrainfig')

I asked Remo to jump back to NSRR when he next has the chance.
