### ISSUE TITLE
Hide comment indicators and comment section on blog posts

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#356]
Given the lack of uptake on blog article comments, let's hide that stuff away.

Hide these things:

![image](https://user-images.githubusercontent.com/707167/67508206-89c10d80-f65e-11e9-995c-8d75a4b6de86.png)

On landing page, tools index, blog index, blog entries.

Hide this on blog articles:

![image](https://user-images.githubusercontent.com/707167/67508248-a3625500-f65e-11e9-895f-501af2e6dddb.png)

**Comment by dguettler** [comment]
@remomueller have a look at https://github.com/nsrr/sleepdata.org/pull/358
