### ISSUE TITLE
Check how @-mentions generate emails to users on data request discussion

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#368]
DM left a comment on a data request that included "support@sleepdata.org" and it looks as if NSRR tried to email the "@sleepdata" user, even though that user is not a data request reviewer.

Review how @-mentions are captured and/or who can be @-mentioned in the first place.

Low priority.

**Comment by remomueller** [comment]
I missed a word boundary at the beginning of the regex that checks for the "@" mentions.
