### ISSUE TITLE
Update team page

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#369]
https://sleepdata.org/team

Move to past contributors: GQ, Sara M, Ary G, Shiqiang Tao, Yan Huang.

Eliminate "Co Investigators" section. Move Shaun P to Principal Investigators (SR and SP).

Add to Team Members: Shyamal Argarwal, Ying Zhang, Kate Nuzzolo.

**Comment by remomueller** [comment]
FYI, contributors can be set by checking the "Contributor" option on the user page, so those can be updated dynamically, I've done this for GQ, Sara, Ary, Shiqiang, and Yan.

**Comment by remomueller** [comment]
Also, team members can be removed there by removing the "Core member" option for them on their user page.

**Comment by remomueller** [comment]
To add Shyamal Argarwal, Ying Zhang, Kate Nuzzolo, go to their user page and select "Core Member".
