### ISSUE TITLE
Data request exports contain mismatched data within

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#370]
From here - https://sleepdata.org/orgs/bwh/exports

I noticed when browsing the different CSV files that "Full_Name" seems to cease being filled in around 60-80% of the way when scrolling through the file. In other words, the agreements near the end of the files would often be missing many of the key informational fields, even with an "approved" status. I then decided to check some of the DataRequestIDs against the listed Full_Name and these did not match.

Perhaps it's pulling columnar data in different ways/steps and not properly aligning them when smushing things together for the final CSV?

**Comment by remomueller** [comment]
The issue here was that data requests without any custom fields entered were not properly showing up as null entries in the array.
