### ISSUE TITLE
Fix data requests stuck in limbo (not quite finished)

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#381]
https://sleepdata.org/reviews/7260
https://sleepdata.org/reviews/7281

DM was finalizing these approvals and the application errored out. One of the application servers may have been acting up at the time. DM has been able to fully sign off on approved data requests since. For the two above he now tries to go in and do his sign off and the application throws an error. The agreements show as "APP" on the data requests index, though I'm not sure how they look on the backend.

Here's a "finalized" approval - https://sleepdata.org/reviews/7282

![image](https://user-images.githubusercontent.com/707167/85426140-11418200-b548-11ea-8466-305412b38a7a.png)

**Comment by remomueller** [comment]
Both of these are approved, I think the issue was saving the signature, which set the state as approved, but did not correctly save the signature. I've set the data requests back to "submitted" state, so they should be able to be approved now.

**Comment by mrueschman** [comment]
DM confirmed the data request sign off went as expected. Closing issue.
