### ISSUE TITLE
Add date of reply to forum post export

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#384]
Follow-up to #371 - add column for date of reply (date created).

Secondary: Add another column for "# of days between date of topic creation and reply creation" (basic purpose: give a glance at how quickly new topics are responded to).

**Comment by remomueller** [comment]
For the secondary item, this is more business logic that makes more sense to be computed outside of the export task itself (as all the data is provided to compute it), and that defining time to first reply may need to be adjusted to "first time to reply by another user", or "first time to reply by a NSRR team member".
