### ISSUE TITLE
Data Request Review page does not show "secondary" reviewer initial bubbles

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#389]
I am setting up the WSC dataset. I added a new organization member (no primary role) and added her (from the Collaborators page) as a reviewer on the WSC dataset. When I submit a data request and go to review it, I see this at the top:

![image](https://user-images.githubusercontent.com/707167/89322697-9f824b00-d652-11ea-8fe2-f921eaa738da.png)

However the new reviewer (AR) does have this request in her queue since it includes WSC and will show up when she approves/rejects. E.g.

![image](https://user-images.githubusercontent.com/707167/89322824-d193ad00-d652-11ea-8fa7-0682bc7cb137.png)

My guess is that only the "primary" reviewers (organization members who globally do reviews) get shown in this area, but it would be nice to have all the assigned reviewers listed from the beginning (i.e. right at data request submission).

**Comment by mrueschman** [comment]
Update: Confirmed that only the 3 bubbles show up when submitting a new data request, even though the 4 reviewers should be assigned. From the Admin Roles page:

![image](https://user-images.githubusercontent.com/707167/89919377-2d1ce800-dbc9-11ea-9629-9ff8bdbec59c.png)

But only 3 bubbles on review.

Thanks for checking!

**Comment by remomueller** [comment]
This ended up being due to only organization reviewers being initially added to the dataset requests. This has been updated, so reviewers of a specific dataset are also added to the reviews.
