### ISSUE TITLE
Impossible percentage displayed on data request organization report

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#390]
From here - https://sleepdata.org/orgs/bwh/reports/data-requests

![image](https://user-images.githubusercontent.com/707167/89548755-69b99f80-d7d5-11ea-8c6a-285a818b3ac9.png)

It dawns on me now that this is probably taking some sort of "approved_at" date, i.e. this could be due to some data requests submitted in July being approved in August? 

Ideally the "Approved" would be "Among the data requests submitted in that month, how many were approved", but if this is tricky then it's probably fine to leave it. We could always derive the "true" monthly percentage using the data request export.

Marking as Data Error, but may just be a quirk.

**Comment by remomueller** [comment]
Yep, the "approved" are any (from any time) that were approved that month. The % could be changed to represent "% of this months that were approved at any time".

**Comment by mrueschman** [comment]
Yes, let's change it to "% of this month's that were approved at any time". Thanks!

**Comment by mrueschman** [comment]
Something still amiss? Reopening for now, though this is not a high priority issue.

![image](https://user-images.githubusercontent.com/707167/90384531-b318b300-e04f-11ea-9fdc-974316aa4497.png)

**Comment by remomueller** [comment]
The approved column should now be more consistent! Thanks.
