### ISSUE TITLE
Odd display bug with two variable folders with similar names

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#392]
https://staging.partners.org/sleepdata.org/datasets/wsc/variables?folder=Sleep+Questionnaires%2FSleep+Disorder

There are folders called "Sleep Disorder" and "Sleep Disordered Breathing". The subset of variables in the latter are also being shown to be in the former, and when navigating to the "Sleep Disorder" folder another subfolder ("ed Breathing") is shown.

![image](https://user-images.githubusercontent.com/707167/90671272-76e97c00-e222-11ea-8c31-1efe48bfd22a.png)

![image](https://user-images.githubusercontent.com/707167/90671342-8f599680-e222-11ea-8593-40541898825a.png)

![image](https://user-images.githubusercontent.com/707167/90671377-9c768580-e222-11ea-80aa-ac77d4046f58.png)

**Comment by remomueller** [comment]
Definitely interesting scenario. Let me know if this appears in other ways (ie two folders named the same, that both have subfolders with the same name, etc)
