### ISSUE TITLE
Dataset variables at root level causing issues in subsequent releases / deploys

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#395]
E.g. the "pcstah3d" variable in SOF shows as being folder-less. https://sleepdata.org/datasets/sof/variables/pcstah3d/ (latest dataset version 0.6.0 - released 2019)

But in 0.6.0 on GitHub: https://github.com/nsrr/sof-data-dictionary/blob/master/variables/Polysomnography%20(PSG)/Sleep%20Architecture/pcstah3d.json

Quote from Teams: My guess is it has something to do with it updating the existing variable on a spout deploy, can dig in more at a later point, but variables at the root are a bit of a special case, my thoughts would be (1) fix bug that prevents existing variables from having their folders updated (2) fix existing variables with that issue so that they don’t require a new spout deploy

May relate to #394.

**Comment by remomueller** [comment]
Looking into this, this is due to the variable itself no longer being part of the dataset CSV itself. This means that Spout doesn't generate graphs for the variable, and doesn't post any update/stats on the variable. Most likely it makes most sense to remove this variable from the dataset as it's a variable that doesn't map to any existing data.

**Comment by remomueller** [comment]
Spout could be also be updated to provide a limited amount of info on these vestigial variables as well. Let me know which approach you'd like to take.

**Comment by remomueller** [comment]
Here's a list of all variables affected by this issue:

```
Variable.where(spout_version: nil).order(:dataset_id).select(&:latest_version_and_released?).collect { |v| puts "#{v.dataset.s
ug} #{v.name}" }
```

```
sof pcstah3d
sof pcstahar
sof pcstahda
numom2b avgdurds_pbd3
homepap diagtype
```

**Comment by remomueller** [comment]
Resolving this issue. Please open an issue in spout if you'd like to go that route, thanks!
