### ISSUE TITLE
Check that @ mentions from data request reviews are working

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#399]
RE: #368 perhaps

I think that after this change any @ mentions have not been going through. I missed a couple from DM in recent weeks. Then I just made one @ DM himself and he has not received an email.

Assuming they are not functioning.

**Comment by remomueller** [comment]
Correct, the word boundary didn't work as expected, I adjusted it to allow mentions at the beginning of the comment, or if there's a space preceding the "@" symbol.
