### ISSUE TITLE
Troubleshoot empty forum topic

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#402]
![image](https://user-images.githubusercontent.com/707167/97618739-c9e76880-19f5-11eb-909b-8cecc4620c9a.png)

First topic goes to this URL: https://sleepdata.org/forum/download-shhs-dataset-with-matlab

![image](https://user-images.githubusercontent.com/707167/97618835-e84d6400-19f5-11eb-846d-997e43d11bb8.png)

The user has an @.jp email address, so I wondered if possibly some Japanese characters caused things to bug out. I couldn't find a way to edit/view the actual post from within sleepdata.org itself.

**Comment by remomueller** [comment]
This post was only a title, the topic appears to have been created without an actual description (which would be the first part of the blog post). I couldn't find any topic "replies" created by the user of the post.
