### ISSUE TITLE
Re-enable sitewide Google Analytics

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#405]
With privacy policy issues (#403 and #404) completed, re-enable Google Analytics sitewide. 

I don't know a whole lot about configuration options, but I had read about IP Anonymization, which seemed like it might be worthwhile to enable.

**Comment by remomueller** [comment]
Can you provide the UA-XXXXX-X account number where you'll be viewing the analytics?

**Comment by mrueschman** [comment]
> Can you provide the UA-XXXXX-X account number where you'll be viewing the analytics?

Sent on Teams, thanks!
