### ISSUE TITLE
Add 'Sign up' button/bubble into main navigation next to 'Sign in'

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#406]
A la github.com...

![image](https://user-images.githubusercontent.com/707167/104662667-5589a080-5699-11eb-854f-0f1453420ed7.png)

Link points to https://sleepdata.org/join

**Comment by mrueschman** [comment]
Reopening this issue to have the outline added (as in screenshot above) with "Sign up" to better distinguish it.

**Comment by remomueller** [comment]
Made minor tweaks to this to display everything better. The nav items were all a bit off, and new "dropdown" menu items were also throwing things off a bit.
