### ISSUE TITLE
Posting replies on forum or comments on data requests causes error

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#415]
E.g. go here - https://staging.partners.org/sleepdata.org/forum/cool-topic/1#write-a-reply

Make a reply, press "Comment", shown page like this --

![image](https://user-images.githubusercontent.com/707167/116014795-07bff500-a605-11eb-8400-e29a08a8dc6c.png)

The reply seems to go through and save, just get pushed to this unexpected output.

ALSO happens when submitting comments on data requests. (Actually goes to "We're sorry something went wrong" page). Comment seems to go through correctly.

**Comment by mrueschman** [comment]
Assume this is all related, but going to a URL like https://sleepdata.org/replies/869 throws an error.

I clicked **link** under wang123's post (i.e. the permanent link to that reply). https://sleepdata.org/forum/dataset-requests

**Comment by remomueller** [comment]
The redirect error was fixed, and was a separate bug from the way remote forms (AJAX) rendered the response from the server. Both have been fixed in the beta that went live (for this and MyApnea).
