### ISSUE TITLE
Prevent data request from submitting twice

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#418]
Can't recall having seen this before - https://www.sleepdata.org/reviews/9623

It's as if the data request was submitted twice - double submission of form?

**Comment by remomueller** [comment]
The form was submitted hours apart, looks like it may have been multiple tabs open (or a refresh of a page). Deleted the redundant agreement event. Let me know if this becomes a common occurrence, and we can make it so you can't submit and already submitted form.
