### ISSUE TITLE
For documentation repositories with only 1 file (README.md), have documentation file structure auto-hide

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#433]
We're moving toward a "single page" documentation style, which makes the right-hand panel for the documentation file structure irrelevant. 

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/707167/209993783-e58de674-b91f-4a11-ad52-1056434291af.png">

In this case, have the page (by default) switch to the "hidden menu" view:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/707167/209993854-4cbc8406-6c6e-4b9a-b339-4cd1157eabcc.png">

(Maybe we'll come up with a better way to utilize a right-hand panel in the future with other things besides the documentation file structure)

**Comment by remomueller** [comment]
This sounds fine, we could also have it try to automatically determine a table of contents that would create anchor links throughout the page if you like.

**Comment by mrueschman** [comment]
Sounds worth trying - if single page, build TOC based on ## sections.

**Comment by remomueller** [comment]
Ok, so single page documentation now automatically creates a table of contents with anchor links that are clickable.
