### ISSUE TITLE
Mousing over main navigation causes 1 pixel bump down

### ISSUE THREAD

**Issue by mrueschman** [nsrr/sleepdata.org#437]
Underline gets added, but rolling over navigation causes 1 pixel (I assume) shift in the content.

Maybe something with the fiddling with the "Sign Up" button caused this.

Seems to happen in both latest Chrome and Edge.

**Comment by remomueller** [comment]
Addressed with cc197a81177f555464a49441a2a7c28e56dc1f4f.
